import * as THREE from "three";import {Application,Text} from "pixi.js";import type {ClientMessage,PlayerInput,ServerMessage,Vec3} from "@forged-arena/protocol";import "./style.css";
const root=document.querySelector<HTMLDivElement>("#app")!,scene=new THREE.Scene();scene.background=new THREE.Color(0x07111f);const camera=new THREE.OrthographicCamera(-16,16,9,-9,.1,100);camera.position.set(15,18,15);camera.lookAt(0,0,0);const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));root.appendChild(renderer.domElement);scene.add(new THREE.HemisphereLight(0xbfe8ff,0x172030,2.4));const sun=new THREE.DirectionalLight(0xffffff,3);sun.position.set(8,15,5);scene.add(sun);scene.add(new THREE.Mesh(new THREE.BoxGeometry(24,.4,14),new THREE.MeshStandardMaterial({color:0x173d35,roughness:.8})));
const ball=new THREE.Mesh(new THREE.SphereGeometry(.35,24,24),new THREE.MeshStandardMaterial({color:0xf5f5f5}));scene.add(ball);const avatars=new Map<string,THREE.Mesh>(),targets=new Map<string,Vec3>();let myId="";const hud=new Application();await hud.init({resizeTo:window,backgroundAlpha:0,antialias:true});hud.canvas.className="hud";root.appendChild(hud.canvas);const title=new Text({text:"FORGED ARENA • WASD MOVE • MOUSE AIM • E PASS • SPACE SHOOT",style:{fill:0xffffff,fontSize:22,fontWeight:"700"}});title.position.set(24,20);hud.stage.addChild(title);
const aimMarker=new THREE.Mesh(new THREE.RingGeometry(.35,.48,32),new THREE.MeshBasicMaterial({color:0xffd84d,side:THREE.DoubleSide}));aimMarker.rotation.x=-Math.PI/2;scene.add(aimMarker);
let aimX=1,aimZ=0;const pointer=new THREE.Vector2(),raycaster=new THREE.Raycaster(),pitchPlane=new THREE.Plane(new THREE.Vector3(0,1,0),0),hit=new THREE.Vector3();
renderer.domElement.addEventListener("pointermove",e=>{const rect=renderer.domElement.getBoundingClientRect();pointer.x=((e.clientX-rect.left)/rect.width)*2-1;pointer.y=-((e.clientY-rect.top)/rect.height)*2+1;raycaster.setFromCamera(pointer,camera);if(!raycaster.ray.intersectPlane(pitchPlane,hit))return;const me=avatars.get(myId);if(!me)return;const dx=hit.x-me.position.x,dz=hit.z-me.position.z,l=Math.hypot(dx,dz);if(l>.1){aimX=dx/l;aimZ=dz/l;}aimMarker.position.set(me.position.x+aimX*2,.23,me.position.z+aimZ*2);});
let ballTarget:Vec3={x:0,y:.55,z:0},seq=0;const keys=new Set<string>(),ws=new WebSocket(import.meta.env.VITE_GAME_SERVER_URL??"ws://localhost:8787");addEventListener("keydown",e=>keys.add(e.code));addEventListener("keyup",e=>keys.delete(e.code));ws.onmessage=e=>{const msg=JSON.parse(e.data) as ServerMessage;if(msg.type==="welcome")myId=msg.payload.playerId;if(msg.type==="snapshot"){ballTarget=msg.payload.ball.position;for(const p of msg.payload.players){targets.set(p.id,p.position);if(!avatars.has(p.id)){const mesh=new THREE.Mesh(new THREE.CapsuleGeometry(.45,1.1,6,12),new THREE.MeshStandardMaterial({color:p.team==="blue"?0x29a8ff:0xff4b4b}));scene.add(mesh);avatars.set(p.id,mesh);}}}};
setInterval(()=>{if(ws.readyState!==WebSocket.OPEN)return;const input:PlayerInput={seq:++seq,moveX:(keys.has("KeyD")?1:0)-(keys.has("KeyA")?1:0),moveZ:(keys.has("KeyS")?1:0)-(keys.has("KeyW")?1:0),aimX,aimZ,sprint:keys.has("ShiftLeft"),pass:keys.has("KeyE"),shoot:keys.has("Space"),tackle:false};ws.send(JSON.stringify({type:"input",payload:input} satisfies ClientMessage));},1000/30);
function resize(){renderer.setSize(innerWidth,innerHeight);const a=innerWidth/innerHeight,h=18;camera.left=-h*a/2;camera.right=h*a/2;camera.top=h/2;camera.bottom=-h/2;camera.updateProjectionMatrix()}addEventListener("resize",resize);resize();function frame(){ball.position.lerp(new THREE.Vector3(ballTarget.x,ballTarget.y,ballTarget.z),.28);for(const [id,m] of avatars){const t=targets.get(id);if(t)m.position.lerp(new THREE.Vector3(t.x,t.y,t.z),id===myId?.38:.25);}renderer.render(scene,camera);requestAnimationFrame(frame)}frame();
